config/routes.rb
Rails.application.routes.draw do

  #トップ画面
  root "users#top"
  #topページからsignin
  get "users/signup"
  #ユーザー登録画面
  post "users/create", to: "users#create"

  #変更画面に移動
  get "users/edit"

  #ユーザー情報変更
  post "users/update", to: "users#update"

  #topページからlogin
  get "users/login"
  #ログイン画面
  post "users/auth", to: "users#auth"
  # マイページへのアクセス
  get "mypages/index"
  #ログアウト
  get "users/destroy"

  # お気に入り登録
  post "favorites/create", to: "favorites#create"
  # お気に入り削除
  delete "favorites/destroy", to: "favorites#destroy"

  #部分テンプレートの設定
  get "mypages/mypages"
  get "mypages/analyses"
  get "mypages/backnumber"

  #検索したときの動作
  get "/searches/index"

  #最適化計算
  post "optimizations/calc", to: "optimizations#calc"

  # ポートフォリオに追加したときに同時に計算もする
  post "analyses/stat", to: "analyses#stat"
  #ポートフォリオを保存する
  post "portfolios/create", to: "portfolios#create"
  # ポートフォリオを削除する
  delete "portfolios/destroy", to: "portfolios#destroy"

  # シミュレートしてみる
  post "simulations/calc",to: "simulations#calc"


  # 時系列分析のトップページ
  get "analyses/index"

  # 時系列データ結果を表示する
  post "analyses/calc",to: "analyses#calc"

  #管理画面
  get "admins/admin"
  #ファイルのアップロード
  post "admins/import", to: "admins#import"

  # API用の試験パス
  # post "lists/greet", to: "lists#greet"
  # post "lists/statistic", to: "lists#statistic"

end

app/models/user.rb
class User < ApplicationRecord

    validates :name, presence: {message:"を入力してください"}
  validates :email, presence: {message:"を入力してください"}
  validates :password, presence: {message:"を入力してください"}
  validates :password_confirmation, presence: true

  #emailの形式指定
  validates :email, format:{with:/[A-Za-z0-9._+]+@[A-Za-z]+.[A-Za-z]/,message:"アドレスを登録してください"}

  # パスワードの文字数を制限
  validates :password, length: {in: 8..32,too_long:"は３２文字以内にしてください",too_short:"は８文字以上にしてください"}

  # パスワードの文字種を制限
  validates :password,format: {with: /(?=.*?[a-z])(?=.*?[A-Z])(?=.*?\d)/,message:"%{value}はアルファベット（大小）と半角数字の混合にしてください"}

  #パスワードが一致しているかの確認
  validates :password,confirmation: {message: "とpasswordの値が一致しません"}

  has_secure_password
  has_many :favorites

  #portfoliosモデルとの関連
  has_many :portfloios
  has_many :groups
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  #トップページ
  def top
  end

  #サインイン画面に遷移
  def signup
    @user=User.new
  end

  #ログイン画面に遷移
  def login
  end

  #登録情報変更画面に遷移
  def edit
  end

  def update
    @user = User.find(current_user.id)

    #検索するだけの場合ストロングパラメータに通す必要はない。
    if @user && @user.authenticate(params[:change][:old_password])
      #データベースに登録する場合、ストロングパラメータに登録する
      if @user.update_attributes(change_params)
        redirect_to root_path
      else
        render 'edit'
      end
    else
      render 'edit'
    end
  end

  # 新規ユーザー登録メゾット
  def create
    @user=User.new(user_params)
    # user=User.new(user)

    if @user.save
      redirect_to root_url
    else
      render :signup
    end
  end

  # ログインアクション
  def auth
    user=User.find_by(email_params)
    if user && user.authenticate(password_params[:password])
      log_in user
      redirect_to mypages_index_path
    else
      render :login
    end
  end

  # ログアウト機能
  def destroy
    log_out
    redirect_to root_url
  end

  private
  #新規会員登録のときのストロングパラメーター
  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end

  #ログインの際のセッション
  def log_in(user)
    session[:user_id]=user.id
  end

  def email_params
    params.require(:session).permit(:email)
  end

  def password_params
    params.require(:session).permit(:password)
  end

  # ユーザー情報変更のときのコード
  def change_params
    params.require(:change).permit(:password,
      :password_confirmation)
  end

  #ログアウトするときのセッション
  def log_out
    session.delete(:user_id)
    @current_user=nil
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="top-bg">
    <div class="container-fluid">
        <div class="row">
            <div class="col-4 offset-4 edit-div-height">
                <!-- login-cardはcard要素の縦方向の位置を決める -->
                <div class="card bg-light shadow edit-div-h-middle">
                    <div class="card-body" style="min-height:500px;">
                        <h3 class="text-center original-text-color">ユーザー情報変更</h1>
                        <%= form_for :change , url: users_update_path do |f|%>
                          <div class="form-group">
                            <%= f.label :old_password,class: "original-text-color"%>
                            <%= f.password_field :old_password,class: "form-control" %>
                          </div>
                          <div  id="pass"class="form-group">
                            <%= f.label :new_password,class: "original-text-color"%>
                            <%= f.password_field :password,class: "form-control" %>
                          </div>
                          <div id="pass_confirm" class="form-group">
                            <%= f.label :password_confirmation,class: "original-text-color" %>
                            <%= f.password_field :password_confirmation,class: "form-control" %>
                          </div>
                          <%= f.submit "変更する",class: "login-btn btn btn-block text-white"%>
                        <% end %>
                        <%= link_to "トップに戻る",root_path,class: "original-text-color"%>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/users/login.html.erb
<div class="top-bg">
    <div class="container-fluid">
        <div class="row">
            <div class="col-4 offset-4 login-div-height">
                <!-- login-cardはcard要素の縦方向の位置を決める -->
                <div class="card bg-light shadow login-div-h-middle">
                    <div class="card-body" style="min-height:350px;">
                        <h3 class="text-center original-text-color">ログイン</h1>
                        <%= form_for :session , url: users_auth_path do |f|%>
                            <div class="form-group">
                                <%= f.label :name, class: 'original-text-color'%>
                                <%= f.text_field :name, class: 'form-control'%>
                            </div>
                            <div class="form-group">
                                <%= f.label :password,class: "original-text-color"%>
                                <%= f.password_field :password,class: "form-control" %>
                            </div>
                            <%= f.submit "Log in",class: "login-btn btn btn-block mt-5 text-white"%>
                        <% end %>
                        <%= link_to "トップへ戻る",root_path,class: "original-text-color"%>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/users/signup.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-4 offset-4 signup-div-height">
            <!-- login-cardはcard要素の縦方向の位置を決める -->
            <div class="card bg-light shadow signup-div-h-middle">
                <div class="card-body" style="min-height:500px;">
                    <h3 class="text-center text-primary">新規ユーザー登録</h1>
                    <%= form_for :user , url: users_create_path do |f|%>
                    <%#= form_for @user do |f|%>
                      <div class="form-group">
                        <%= f.label :name, class: 'text-primary'%>
                        <%= f.text_field :name, class: 'form-control'%>

                        <% if @user.errors.any? %>
                          <% @user.errors.full_messages_for(:name).each do |message| %>
                           <p class="text-primary"><%= message %></p>
                          <% end %>
                        <% end %>

                      </div>
                      <div class="form-group">
                        <%= f.label :email, class: "text-primary"%>
                        <%= f.text_field :email, class: "form-control"%>

                        <% if @user.errors.any? %>
                          <% @user.errors.full_messages_for(:email).each do |message| %>
                            <p class="text-primary"><%= message %></p>
                          <% end %>
                        <% end %>

                      </div>
                      <div class="form-group">
                        <%= f.label :password,class: "text-primary"%>
                        <%= f.password_field :password,class: "form-control" %>

                        <% if @user.errors.any? %>
                          <% @user.errors.full_messages_for(:password).each do |message| %>
                            <p class="text-primary"><%= message %></p>
                          <% end %>
                        <% end %>

                      </div>
                      <div class="form-group">
                        <%= f.label :password_confirmation,class: "text-primary" %>
                        <%= f.password_field :password_confirmation,class: "form-control" %>

                        <% if @user.errors.any? %>
                          <% @user.errors.full_messages_for(:password_confirmation).each do |message| %>
                            <p class="text-primary"><%= message %></p>
                          <% end %>
                        <% end %>

                      </div>
                      <%= f.submit "登録",class: "btn btn-block btn-primary"%>
                    <% end %>
                    <%= link_to "ログインはこちら",root_path,class: "text-primary"%>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/users/top.html.erb
<div class="top-bg">
    <div class="container-fluid">
        <div class="row">
            <div class="col-6 offset-3 top-div-height">
                <div class="top-div-h-middle">
                    <div class="text-center mb-5 pb-5">
                        <div class="h1 inline-block text-white">Safety</div>
                        <div class="inline-block text-white">
                            <i class="fas fa-hand-holding-usd fa-7x"></i>
                        </div>
                    </div>
                    <div class="col-5 inline-block">
                      <%= button_to "Sign up", {controller: 'users', action: 'signup'}, {method: :get,class: 'toppage-btn btn btn-block btn-primary'} %>
                    </div>

                    <% if logged_in? %>
                        <div class="col-5 offset-1 inline-block">
                            <%= button_to "Log in", {controller: 'mypages', action: 'index'}, {method: :get,class: 'toppage-btn btn btn-block btn-primary'}%>
                        </div>
                    <% else %>
                        <div class="col-5 offset-1 inline-block">
                            <%= button_to "Log in", {controller: 'users', action: 'login'}, {method: :get,class: 'toppage-btn btn btn-block btn-primary'}%>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>